### ISSUE TITLE
Not being able to run the web application not even using the example files

### ISSUE THREAD

**Issue by iza-mcac** [dicleyalcin/dbCGI#1]
![image](https://user-images.githubusercontent.com/66480336/114726863-1dcfda80-9d14-11eb-9744-b14332d8aa23.png)

**Comment by dicleyalcin** [comment]
The APIs and some database settings may be misconfigured as we are in the process of migrating the app. An updated and improved version of dbCGI will be pushed (hopefully within a month). I apologize for the inconvenience and will notify users as soon as possible!

Closing this issue in the meantime.
