### ISSUE TITLE
Unable to run web app due to path issue

### ISSUE THREAD

**Issue by michaelodear** [dicleyalcin/dbCGI#2]
Hi,

Recently I tried to use the web app with chromosomal locations to identify genes near chromosomal locations of interest. Unfortunately this error occurred, which seems to be because curpath2 is being handled as a NoneType? (odd since it looks like a string in the local vars). Is this due to the ongoing migration I saw mentioned in the other issue? Since the variable isn't dependent on user input I assume that it is a global issue with the tool currently. If so, I'd love to be notified when it's finished!

![image](https://user-images.githubusercontent.com/47711697/118093265-8c39b280-b410-11eb-9365-e49309a25915.png)

Thanks for all your help.

**Comment by dicleyalcin** [comment]
You are absolutely right, we are still working on migrating our web app (but with additional functionalities) to a new server. I apologize for the delay and will certainly let you know once it's deployed. My guess is within 2-3 weeks. Thank you for your interest!!
